title: Exismys
description: I don't know yet. Maybe a blog about whatever comes to mind. Math, Physics, Programming, whatever. BTW Exismys is short for "Existence is mysterious".
baseurl: ""
url: "https://exismys.github.io"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-sitemap